export const endpointGroups = [
  {
    id: 'auth',
    label: 'Auth',
    endpoints: [
      {
        name: 'Register user',
        method: 'POST',
        path: '/api/v1/auth/register',
        auth: false,
        body: { fullName: 'Demo User', email: 'demo@example.com', password: 'StrongPass123', phone: '9999999999' },
      },
      {
        name: 'Register admin',
        method: 'POST',
        path: '/api/v1/auth/register-admin',
        auth: false,
        headers: { 'X-Admin-Setup-Key': 'change-this-admin-bootstrap-key' },
        body: { fullName: 'Admin User', email: 'admin2@ecommerce.local', password: 'Admin@12345', phone: '9999999999' },
      },
      {
        name: 'Login',
        method: 'POST',
        path: '/api/v1/auth/login',
        auth: false,
        body: { email: 'admin@amazon.local', password: 'admin123' },
      },
      {
        name: 'Refresh token',
        method: 'POST',
        path: '/api/v1/auth/refresh',
        auth: false,
        body: { refreshToken: '' },
      },
      {
        name: 'Logout',
        method: 'POST',
        path: '/api/v1/auth/logout',
        auth: false,
        body: { refreshToken: '' },
      },
    ],
  },
  {
    id: 'products',
    label: 'Products',
    endpoints: [
      {
        name: 'Search products',
        method: 'GET',
        path: '/api/v1/products/search',
        auth: false,
        query: { keyword: '', categoryId: '', brand: '', minPrice: '', maxPrice: '', active: '', sortBy: 'createdAt', sortDir: 'desc', page: 0, size: 20 },
      },
      { name: 'Search products alias', method: 'GET', path: '/api/v1/search/products', auth: false, query: { keyword: '', page: 0, size: 20 } },
      { name: 'Featured products', method: 'GET', path: '/api/v1/products/featured', auth: false, query: { limit: 10 } },
      { name: 'Get product by ID', method: 'GET', path: '/api/v1/products/{productId}', auth: false, params: { productId: '' } },
      { name: 'Get product by slug', method: 'GET', path: '/api/v1/products/slug/{slug}', auth: false, params: { slug: '' } },
      {
        name: 'Admin search products',
        method: 'GET',
        path: '/api/v1/admin/products/search',
        query: { keyword: '', active: '', page: 0, size: 20 },
      },
      {
        name: 'Create product',
        method: 'POST',
        path: '/api/v1/admin/products',
        body: {
          name: 'Sample Product',
          slug: 'sample-product',
          description: 'Sample description',
          price: 999.99,
          discountPrice: null,
          active: true,
          brand: 'DemoBrand',
          sku: 'SKU-1001',
          categoryId: null,
          imageUrls: [],
          stockQuantity: 50,
          lowStockThreshold: 5,
        },
      },
      {
        name: 'Update product',
        method: 'PUT',
        path: '/api/v1/admin/products/{productId}',
        params: { productId: '' },
        body: {
          name: 'Updated Product',
          slug: 'updated-product',
          description: 'Updated description',
          price: 1099.99,
          discountPrice: null,
          active: true,
          brand: 'DemoBrand',
          sku: 'SKU-1001',
          categoryId: null,
          imageUrls: [],
          stockQuantity: 25,
          lowStockThreshold: 5,
        },
      },
      { name: 'Delete product', method: 'DELETE', path: '/api/v1/admin/products/{productId}', params: { productId: '' } },
    ],
  },
  {
    id: 'categories',
    label: 'Categories',
    endpoints: [
      { name: 'Category tree', method: 'GET', path: '/api/v1/categories/tree', auth: false },
      { name: 'Get category', method: 'GET', path: '/api/v1/categories/{categoryId}', auth: false, params: { categoryId: '' } },
      { name: 'Admin list categories', method: 'GET', path: '/api/v1/admin/categories' },
      { name: 'Create category', method: 'POST', path: '/api/v1/admin/categories', body: { name: 'Sample Category', slug: 'sample-category', description: '', imageUrl: '', parentId: null } },
      { name: 'Update category', method: 'PUT', path: '/api/v1/admin/categories/{categoryId}', params: { categoryId: '' }, body: { name: 'Updated Category', slug: 'updated-category', description: '', imageUrl: '', parentId: null } },
      { name: 'Delete category', method: 'DELETE', path: '/api/v1/admin/categories/{categoryId}', params: { categoryId: '' } },
    ],
  },
  {
    id: 'users',
    label: 'Users',
    endpoints: [
      { name: 'List users', method: 'GET', path: '/api/v1/admin/users' },
      { name: 'Update user status', method: 'PATCH', path: '/api/v1/admin/users/{userId}/status', params: { userId: '' }, body: { active: true } },
      { name: 'Delete user', method: 'DELETE', path: '/api/v1/admin/users/{userId}', params: { userId: '' } },
    ],
  },
  {
    id: 'cart',
    label: 'Cart',
    endpoints: [
      { name: 'Get cart', method: 'GET', path: '/api/v1/cart' },
      { name: 'Add cart item', method: 'POST', path: '/api/v1/cart/items', body: { productId: '', quantity: 1 } },
      { name: 'Update cart item', method: 'PUT', path: '/api/v1/cart/items/{cartItemId}', params: { cartItemId: '' }, body: { quantity: 2 } },
      { name: 'Remove cart item', method: 'DELETE', path: '/api/v1/cart/items/{cartItemId}', params: { cartItemId: '' } },
    ],
  },
  {
    id: 'wishlist',
    label: 'Wishlist',
    endpoints: [
      { name: 'Get wishlist', method: 'GET', path: '/api/v1/wishlist' },
      { name: 'Add wishlist item', method: 'POST', path: '/api/v1/wishlist/items/{productId}', params: { productId: '' } },
      { name: 'Remove wishlist item', method: 'DELETE', path: '/api/v1/wishlist/items/{wishlistItemId}', params: { wishlistItemId: '' } },
      { name: 'Move wishlist item to cart', method: 'POST', path: '/api/v1/wishlist/items/{wishlistItemId}/move-to-cart', params: { wishlistItemId: '' }, query: { quantity: 1 } },
    ],
  },
  {
    id: 'addresses',
    label: 'Addresses',
    endpoints: [
      { name: 'List addresses', method: 'GET', path: '/api/v1/addresses' },
      { name: 'Create address', method: 'POST', path: '/api/v1/addresses', body: { fullName: 'Demo User', phone: '9999999999', addressLine1: '123 Main St', addressLine2: '', city: 'Mumbai', state: 'Maharashtra', postalCode: '400001', country: 'India', addressType: 'HOME', isDefault: true } },
      { name: 'Update address', method: 'PUT', path: '/api/v1/addresses/{addressId}', params: { addressId: '' }, body: { fullName: 'Demo User', phone: '9999999999', addressLine1: '123 Main St', addressLine2: '', city: 'Mumbai', state: 'Maharashtra', postalCode: '400001', country: 'India', addressType: 'HOME', isDefault: true } },
      { name: 'Delete address', method: 'DELETE', path: '/api/v1/addresses/{addressId}', params: { addressId: '' } },
    ],
  },
  {
    id: 'orders',
    label: 'Orders',
    endpoints: [
      { name: 'Place order', method: 'POST', path: '/api/v1/orders', body: { addressId: null, shippingAddress: { fullName: 'Demo User', phone: '9999999999', addressLine1: '123 Main St', addressLine2: '', city: 'Mumbai', state: 'Maharashtra', postalCode: '400001', country: 'India' }, couponCode: '', paymentMethod: 'COD' } },
      { name: 'List my orders', method: 'GET', path: '/api/v1/orders' },
      { name: 'Get my order', method: 'GET', path: '/api/v1/orders/{orderId}', params: { orderId: '' } },
      { name: 'Cancel my order', method: 'POST', path: '/api/v1/orders/{orderId}/cancel', params: { orderId: '' } },
      { name: 'Admin list orders', method: 'GET', path: '/api/v1/admin/orders' },
      { name: 'Admin get order', method: 'GET', path: '/api/v1/admin/orders/{orderId}', params: { orderId: '' } },
      { name: 'Admin update order status', method: 'PATCH', path: '/api/v1/admin/orders/{orderId}/status', params: { orderId: '' }, body: { orderStatus: 'SHIPPED' } },
    ],
  },
  {
    id: 'coupons',
    label: 'Coupons',
    endpoints: [
      { name: 'Validate coupon', method: 'POST', path: '/api/v1/coupons/validate', auth: false, body: { code: 'SAVE10', orderAmount: 1000 } },
      { name: 'List coupons', method: 'GET', path: '/api/v1/admin/coupons' },
      { name: 'Create coupon', method: 'POST', path: '/api/v1/admin/coupons', body: { code: 'SAVE10', discountType: 'PERCENTAGE', discountValue: 10, minOrderAmount: 100, maxDiscountAmount: 500, usageLimit: 100, active: true, expiryDate: '2030-12-31T23:59:59' } },
      { name: 'Update coupon', method: 'PUT', path: '/api/v1/admin/coupons/{couponId}', params: { couponId: '' }, body: { code: 'SAVE10', discountType: 'PERCENTAGE', discountValue: 10, minOrderAmount: 100, maxDiscountAmount: 500, usageLimit: 100, active: true, expiryDate: '2030-12-31T23:59:59' } },
      { name: 'Deactivate coupon', method: 'DELETE', path: '/api/v1/admin/coupons/{couponId}', params: { couponId: '' } },
    ],
  },
  {
    id: 'inventory',
    label: 'Inventory',
    endpoints: [
      { name: 'Get inventory by product', method: 'GET', path: '/api/v1/admin/inventory/product/{productId}', params: { productId: '' } },
      { name: 'Update inventory', method: 'PUT', path: '/api/v1/admin/inventory', body: { productId: '', stockQuantity: 50, lowStockThreshold: 5 } },
    ],
  },
  {
    id: 'reviews',
    label: 'Reviews',
    endpoints: [
      { name: 'Create or update review', method: 'POST', path: '/api/v1/reviews', body: { productId: '', rating: 5, title: 'Good product', body: 'Works as expected.' } },
      { name: 'Get approved product reviews', method: 'GET', path: '/api/v1/reviews/product/{productId}', auth: false, params: { productId: '' }, query: { page: 0, size: 10 } },
      { name: 'Moderate review', method: 'PATCH', path: '/api/v1/admin/reviews/{reviewId}/moderate', params: { reviewId: '' }, body: { status: 'APPROVED' } },
    ],
  },
  {
    id: 'payments',
    label: 'Payments',
    endpoints: [
      { name: 'Payment methods', method: 'GET', path: '/api/v1/payments/methods', auth: false },
      { name: 'Initiate payment', method: 'POST', path: '/api/v1/payments/initiate', body: { orderId: '', paymentMethod: 'UPI' } },
      { name: 'Mock complete payment', method: 'POST', path: '/api/v1/payments/mock-complete', body: { orderId: '', paymentMethod: 'UPI' } },
      { name: 'Verify payment', method: 'POST', path: '/api/v1/payments/verify', body: { orderId: '', razorpayOrderId: 'rpay_order_xxx', razorpayPaymentId: 'pay_xxx', signature: 'hex_hmac_signature' } },
      { name: 'Get payment for order', method: 'GET', path: '/api/v1/payments/order/{orderId}', params: { orderId: '' } },
    ],
  },
  {
    id: 'meta',
    label: 'Meta',
    endpoints: [
      { name: 'Order statuses', method: 'GET', path: '/api/v1/meta/order-statuses', auth: false },
      { name: 'Payment methods meta', method: 'GET', path: '/api/v1/meta/payment-methods', auth: false },
    ],
  },
  {
    id: 'demo',
    label: 'Demo',
    endpoints: [
      { name: 'Bootstrap demo data', method: 'POST', path: '/api/v1/demo/bootstrap', auth: false, headers: { 'X-Bootstrap-Key': 'change-this-admin-bootstrap-key' } },
      { name: 'Clear all carts', method: 'POST', path: '/api/v1/demo/clear-all-carts', auth: false, headers: { 'X-Bootstrap-Key': 'change-this-admin-bootstrap-key' } },
    ],
  },
];

export const allEndpoints = endpointGroups.flatMap((group) =>
  group.endpoints.map((endpoint) => ({ ...endpoint, group: group.label })),
);
