spring.application.name=ecommerce-api

# Data source
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/ecommerce_v2?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root123}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Flyway
spring.flyway.baseline-on-migrate=true

# JWT
app.jwt.secret=Y0xrNGFVc2VyVmVyeVNlY3VyZVNlY3JldEtleUZvckpXVFRva2Vuc0luUHJvZHVjdGlvbjI1NkJpdE1pbg==
app.jwt.expiration=900000
app.jwt.refresh-expiration=604800000

# Payment
app.payment.signature-secret=change-me-before-production

# Admin bootstrap
app.admin.bootstrap-key=change-this-admin-bootstrap-key

# OpenAPI / Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha

# Disable Flyway validation
spring.flyway.validate-on-migrate=false

# Server
server.port=8080